insta/api/urls.py
from django.urls import path, include
from .views import (
    PostListView,
    PostCreateView,
    like_post,
    comment_form

)

app_name = 'api'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('like/', like_post, name="like-post"),
    path('commented/', comment_form, name="comment-form"),
]

insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^liked/', views.Likelist.as_view()),
    url(r'^commented/', views.CommentApi.as_view()),
    url(r'^commented/<int:id_post>/', views.CommentApi.as_view()),
    url(r'^posted/', views.Postlist.as_view()),
    path('', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/api/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, AnonymousUser, User
from typing import Union

# Create your models here.

class BaseModel(models.Model):
    """Base model for the application. Uses UUID for pk."""
    id = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid.uuid4,
    )
    class Meta:
        abstract = True

class User(BaseModel, AbstractUser):
    profile_picture = models.ImageField(('profile_picture'),upload_to="photos",blank=True)
    bio = models.CharField(blank=True, null=True, max_length=250)

    def __str__(self):
        return self.username

RequestUser = Union[AnonymousUser, User]       


class Post(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    photo = models.ImageField(blank=True, null=True)

    caption = models.TextField()
    #comments = models.ForeignKey(Comment, editable=True, blank=True, null=True, on_delete=models.CASCADE )
    #likes = models.ForeignKey(Like, blank=True, null=True, on_delete=models.CASCADE)
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.caption

    def get_image_url(self, obj):
        return obj.image.url

    @property
    def num_likes(self):
        return self.liked.all().count()

    class Meta:
        ordering = ["-created_at"]



LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(BaseModel):
    #likes=models.ManyToManyField(User,blank=True, related_name='likes')
     
    # @property
    # def total_likes(self):
    #     return self.likes

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

    def __str__(self):
        return str(self.post)


class Comment(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post,related_name="comments", on_delete=models.CASCADE, null=True)
    content = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-created_at"]

insta/api/forms.py
from django import forms
from .models import Post, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

class PostForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Post', 'Post', css_class='btn-primary'))

    class Meta:
        model = Post
        fields = [
            'photo',
            'caption'
        ]

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea', 'name': 'comment'}), required=True)

    class Meta:
        model = Comment
        fields = [
            'content',
        ]   

insta/api/views.py
from django.shortcuts import render, redirect , get_object_or_404, HttpResponseRedirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics
from django.contrib import messages
from . serializers import LikeSerializer, CommentSerializer, PostSerializer
from .models import Post, Like, Comment
from .forms import PostForm, CommentForm
from django.views.generic import (
    ListView,
    CreateView,
)
# Create your views here.

class PostListView(ListView):
    template_name = "api/post_list.html"
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3

class PostCreateView(CreateView):
    template_name = "api/post_create.html"
    form_class = PostForm
    queryset = Post.objects.all()
    success_url = '/'

    def form_valid(self, form):
        print(form.cleaned_data)
        form.instance.author = self.request.user 
        return super().form_valid(form)


def like_post(request):
    # print('This method works HURRAY!!!!')
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)
        
        like, created = Like.objects.get_or_create(user=user, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'

        like.save()
    return redirect('api:post_list')
    
def comment_form(request):
    comments = Comment.objects.filter(user=request.user)
    form = CommentForm()
    if request.method =='POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            
            messages.success(request,('Your new comment has been added'))
        return redirect('/')

    content = {'Comments':comments, 'form':form}
    return render(request, 'api/post_list.html', content)
    

class Likelist(APIView):
    def get(self, request):
        like1 = Like.objects.all()
        serializer = LikeSerializer(like1, many=True)
        return Response(serializer.data)

    def post(self):
        pass

class Commentlist(APIView):
    def get(self, request):
        comment1 = Comment.objects.all()
        serializer = LikeSerializer(comment1, many=True)
        return Response(serializer.data)

    def post(self, request):
        comment = request.data()

class Postlist(APIView):
    def get(self, request):
        post1 = Post.objects.all()
        serializer = PostSerializer(post1, many=True)
        return Response(serializer.data)

    def post(self):
        pass

class CommentApi(APIView):
    serializer_class = CommentSerializer
    def post(self , request, id_post, *args, **kwargs):
        post = Post.objects.get(id=self.kwargs['id_post'])
        comment = request.data["comment"]
        post.comment.add(comment)
        post.save()
        return Response({"response" : "comment"})

insta/api/templates/api/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/apis.css' %}">
    <title>Document</title>
</head>
<body>
    <header>
        <div class='navigation'>
            <div class='instalogo'>
                <a class='' href='/'> <i class="fab fa-instagram"></i></a>
                <a class='vl' href='/'></a>
                <a href=''>Instagram</a>
            </div>
            <div class='search_bar'>
                <input type="text" placeholder='search'>
                <a class='search' href=''><i class="fas fa-search"></i></a>
            </div>
            <div class='contacts_icons'>
                <a class='explore' href='/'><i class="far fa-compass"></i></a>
                <a class='likes' href='/'><i class="far fa-heart"></i></a>
                <a class='profile' href='/'><i class="far fa-user"></i></a>
            </div>
        </div>
    </header>
    <div class='content_container'>
        {% block content %}
        
        {% endblock %}

    </div>
    
</body>
</html>

insta/api/templates/api/post_create.html
{% extends 'api/base.html' %}
{% load crispy_forms_tags %}

{%  block content %}
    <div class=" panel panel-default" style="width: 500px; margin: 0 auto;">
        <div class="panel-body">
            {% crispy form %}
            {% csrf_token %}

        </div>
    </div>

{% endblock %}

insta/api/templates/api/post_list.html
{% extends 'api/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <div class="card_header">
                <div class="profile_image">

                </div>
                <div class="post_info">
                    <div class="post_name">{{ post.author }}</div>
                    <div class="post_location">Dnipro</div>
                </div>
                <div class="post_options"><i class="fas fa-ellipsis-h"></i></div>

            </div>
            <div class="post_image">
                <img src="{{ post.photo.url }}"alt="">
            </div>
            <div class="engagement">
                <!-- <a href=""><i class="far fa-heart"></i></a> -->
                <form action="{% url 'api:like-post'%}" method='POST' class="ui form" style="display: inline-block;margin: 0;margin-block-end: 0;">
                    {% csrf_token %}
                    <input type='hidden' name='post_id' value="{{ post.id }}">
                    <button type="submit" style="outline: none;background: none;border: 0;width: 40px;height: 40px;padding: 0;display: inline-block;
                "><i class="far fa-heart" style="transform: scale(2);"></i></button>

                </form>

                
                <!-- <a href=""><i class="far fa-comment"></i></a> -->
                <button style="outline: none;background: none;border: 0;width: 40px;height: 40px;padding: 0;display: inline-block;
                "><i class="far fa-comment" style="transform: scale(2);"></i></button>


                <a href=""><i class="far fa-share-square"></i></a>
                <a href=""><i class="far fa-bookmark"></i></a>
            </div>
            <div class="likes">
                <strong>{{ post.liked.all.count }}</strong>
            </div>
            <div class="caption">
                <a href=""><h2> {{ post.author }}</h2></a>
                <span><p>{{ post.caption }}</p></span>
            </div>
            <div class="time_period">
                {{post.created_at | timesince }} ago
            </div>

            <div class="comment_box">
                <textarea placeholder="Add a comment"></textarea>
                <form action="{% url 'api:comment-form'%}" method="POST">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <input type='hidden' value="{{ comment.content }}">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
            </div>
            <div class="card-body">
                {% for comment in comments %}
                <ul class="list-group t20"></ul>
                    <li class="list-group-item">
                      <span class="">{{comment}}</span>
                    </li>
                    {% endfor %}
                </ul>
              </div>
        </div>

    {% endfor %}
    <div class="pagination">
        {% if is_paginated %}
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}"> NEXT &raquo;</a></li>

    {% endif %}
  </ul>
  </nav>
</div>
{% endif %}
    </div>

{% endblock %}    